import apple from "./apple.png";
import banana from "./banana.png";
import milk from "./milk.png";
import bread from "./snacks.png";
import juice from "./drinks.png";
import chips from "./meat_seafood.png";
import eggs from "./dairy_eggs.png";
import cheese from "./cheese.png";
import tomato from "./tomato.png";
import carrot from "./carrot.jpg";

// export const dummyProducts = [
//   {
//     _id: "1",
//     name: "Fresh Apple",
//     image: apple,
//     price: 120,
//     discount: 10,
//     rating: 4.5,
//     reviewCount: 120,
//   },
//   {
//     _id: "2",
//     name: "Banana",
//     image: banana,
//     price: 60,
//     discount: 5,
//     rating: 4.2,
//     reviewCount: 80,
//   },
//   {
//     _id: "3",
//     name: "Milk",
//     image: milk,
//     price: 50,
//     discount: 1,
//     rating: 4.8,
//     reviewCount: 200,
//   },
//   {
//     _id: "4",
//     name: "Bread",
//     image: bread,
//     price: 40,
//     discount: 15,
//     rating: 4.1,
//     reviewCount: 50,
//   },
//   {
//     _id: "5",
//     name: "Orange Juice",
//     image: juice,
//     price: 90,
//     discount: 8,
//     rating: 4.6,
//     reviewCount: 110,
//   },
//   {
//     _id: "6",
//     name: "Potato Chips",
//     image: chips,
//     price: 30,
//     discount: 20,
//     rating: 4.0,
//     reviewCount: 95,
//   },
//   {
//     _id: "7",
//     name: "Eggs",
//     image: eggs,
//     price: 75,
//     discount: 4,
//     rating: 4.7,
//     reviewCount: 140,
//   },
//   {
//     _id: "8",
//     name: "Cheese",
//     image: cheese,
//     price: 180,
//     discount: 12,
//     rating: 4.3,
//     reviewCount: 60,
//   },
//   {
//     _id: "9",
//     name: "Tomato",
//     image: tomato,
//     price: 45,
//     discount: 5,
//     rating: 4.4,
//     reviewCount: 85,
//   },
//   {
//     _id: "10",
//     name: "Carrot",
//     image: carrot,
//     price: 55,
//     discount: 7,
//     rating: 4.5,
//     reviewCount: 72,
//   },
// ];
export const dummyProducts = [
  {
    _id: "1",
    name: "Fresh Apple",
    image: apple,
    price: 120,
    originalPrice: 135,
    unit: "kg",
    category: "fruits-vegetables",
    stock: 20,
    discount: 10,
    rating: 4.5,
    reviewCount: 120,
    isOrganic: true,
    description: "Fresh and juicy apples packed with natural sweetness and essential nutrients. Perfect for healthy snacks, juices, and salads.",
    createdAt: new Date().toISOString()
  },
  {
    _id: "2",
    name: "Banana",
    image: banana,
    price: 60,
    originalPrice: 65,
    unit: "dozen",
    category: "fruits-vegetables",
    stock: 20,
    discount: 5,
    rating: 4.2,
    reviewCount: 80,
    isOrganic: true,
    description: "Naturally ripened bananas rich in potassium and fiber. Ideal for breakfast, smoothies, and energy-packed snacks",
    createdAt: new Date().toISOString()
  },
  {
    _id: "3",
    name: "Milk",
    image: milk,
    price: 50,
    originalPrice: 55,
    unit: "L",
    category: "dairy-eggs",
    stock: 20,
    discount: 1,
    rating: 4.8,
    reviewCount: 200,
    isOrganic: false,
    description: "Pure and fresh milk rich in calcium and protein. Suitable for tea, coffee, cereals, and everyday nutrition.",
    createdAt: new Date().toISOString()
  },
  {
    _id: "4",
    name: "Bread",
    image: bread,
    price: 40,
    originalPrice: 47,
    unit: "pack",
    category: "snacks",
    stock: 20,
    discount: 15,
    rating: 4.1,
    reviewCount: 50,
    isOrganic: false,
    description: "Soft and freshly baked bread made with quality ingredients. Great for sandwiches, toast, and quick meals.",
    createdAt: new Date().toISOString()
  },
  {
    _id: "5",
    name: "Orange Juice",
    image: juice,
    price: 90,
    originalPrice: 98,
    unit: "L",
    category: "fruits",
    stock: 20,
    discount: 8,
    rating: 4.6,
    reviewCount: 110,
    isOrganic: true,
    description: "Refreshing orange juice made from fresh oranges. Rich in vitamin C and perfect for a healthy start to your day.",
    createdAt: new Date().toISOString()
  },
  {
    _id: "6",
    name: "Potato Chips",
    image: chips,
    price: 30,
    originalPrice: 38,
    unit: "pack",
    category: "snacks",
    stock: 20,
    discount: 20,
    rating: 4.0,
    reviewCount: 95,
    isOrganic: false,
    description: "Crispy and delicious potato chips with a satisfying crunch. Perfect for snacking anytime and sharing with friends.",
    createdAt: new Date().toISOString()
  },
  {
    _id: "7",
    name: "Eggs",
    image: eggs,
    price: 75,
    originalPrice: 80,
    unit: "dozen",
    category: "dairy-eggs",
    stock: 20,
    discount: 4,
    rating: 4.7,
    reviewCount: 140,
    isOrganic: true,
    description: "Farm-fresh eggs packed with protein and essential nutrients. Ideal for breakfast, baking, and healthy meals.",
    createdAt: new Date().toISOString()
  },
  {
    _id: "8",
    name: "Cheese",
    image: cheese,
    price: 180,
    originalPrice: 205,
    unit: "pack",
    category: "frozen-foods",
    stock: 20,
    discount: 12,
    rating: 4.3,
    reviewCount: 60,
    isOrganic: false,
    description: "Creamy and flavorful cheese made from high-quality milk. Perfect for sandwiches, pizzas, and pasta dishes.",
    createdAt: new Date().toISOString()
  },
  {
    _id: "9",
    name: "Tomato",
    image: tomato,
    price: 45,
    originalPrice: 50,
    unit: "kg",
    category: "fruits-vegetables",
    stock: 20,
    discount: 5,
    rating: 4.4,
    reviewCount: 85,
    isOrganic: true,
    description: "Fresh and ripe tomatoes rich in vitamins and antioxidants. Suitable for salads, curries, soups, and sauces.",
    createdAt: new Date().toISOString()
  },
  {
    _id: "10",
    name: "Carrot",
    image: carrot,
    price: 55,
    originalPrice: 60,
    unit: "kg",
    category: "fruits-vegetables",
    stock: 20,
    discount: 7,
    rating: 4.5,
    reviewCount: 72,
    isOrganic: true,
    description: "Crunchy and nutritious carrots loaded with vitamins and fiber. Great for salads, juices, and healthy cooking.",
    createdAt: new Date().toISOString()
  },
];